beta/config/routes.rb
Rails.application.routes.draw do
  resources :directories

  resources :usuarios

  resources :posts
  resources :usuario_sessions
  get 'login' => 'usuario_sessions#new' , as: :login
  get 'logout' => 'usuario_sessions#destroy' , as: :logout

end

beta/app/models/directory.rb
class Directory < ActiveRecord::Base
	validates :usuario_rut, length: { in: 8..12 , message: "debe tener entre 8 y 12 caracteres"}
	validates :nombre, :presence => {:message => "Usted debe ingresar un nombre"}
 	validates :descripcion, :presence => {:message => "Usted debe ingresar una descripcion"}
 	validates :telefono, numericality: { only_integer: true }
 	validates :celular, numericality: { only_integer: true }
 	validates :comuna, :presence => {:message => "Usted debe ingresar una comuna"}
 	validates :ciudad, :presence => {:message => "Usted debe ingresar una ciudad"}
end

beta/app/models/usuario.rb
class Usuario < ActiveRecord::Base
	validates :rut, length: { in: 8..12 , message: "debe tener entre 8 y 12 caracteres"}
	validates :rut, uniqueness: {case_sensitive: false ,message: "ya esta registrado"}
	validates :nombre, :presence => {:message => "Usted debe ingresar un nombre"}
 	validates :apellidos, :presence => {:message => "Usted debe ingresar un apellido"}
 	validates :email, :presence => {:message => "Usted debe ingresar un email"}
 	validates :email, uniqueness: {case_sensitive: false ,message: "ya esta registrado"}
 	validates :username, :presence => {:message => "Usted debe ingresar un username"}
 	validates :username, uniqueness: {case_sensitive: false ,message: "ya esta registrado"}
 	validates :password, :presence => {:message => "Usted debe ingresar un password"}
 	#has_secure_password
end

beta/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

beta/app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController
  before_action :set_directory, only: [:show, :edit, :update, :destroy]

  # GET /directories
  # GET /directories.json
  def index
    @directories = Directory.all
  end

  # GET /directories/1
  # GET /directories/1.json
  def show
  end

  # GET /directories/new
  def new
    @directory = Directory.new
  end

  # GET /directories/1/edit
  def edit
  end

  # POST /directories
  # POST /directories.json
  def create
    @directory = Directory.new(directory_params)

    respond_to do |format|
      if @directory.save
        format.html { redirect_to @directory, notice: 'Directory was successfully created.' }
        format.json { render :show, status: :created, location: @directory }
      else
        format.html { render :new }
        format.json { render json: @directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directories/1
  # PATCH/PUT /directories/1.json
  def update
    respond_to do |format|
      if @directory.update(directory_params)
        format.html { redirect_to @directory, notice: 'Directory was successfully updated.' }
        format.json { render :show, status: :ok, location: @directory }
      else
        format.html { render :edit }
        format.json { render json: @directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directories/1
  # DELETE /directories/1.json
  def destroy
    @directory.destroy
    respond_to do |format|
      format.html { redirect_to directories_url, notice: 'Directory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_directory
      @directory = Directory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def directory_params
      params.require(:directory).permit(:usuario_rut, :nombre, :descripcion, :telefono, :celular, :comuna, :ciudad)
    end
end

beta/app/controllers/usuario_sessions_controller.rb
class UsuarioSessionsController < ApplicationController
  def new
  end

 def create
  usuario = Usuario.find_by_username(params[:username])
  if usuario && Usuario.find_by_password(params[:password])
    session[:usuario_id] = usuario.id
    render :text => "Login exitoso", :status => 500
  else
    render :text => "This is an error", :status => 500
  end
end

  def destroy
    session[:usuario_id] = nil
   	render "new"
  end
end

beta/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:rut, :nombre, :apellidos, :email, :username, :password)
    end
end

beta/app/helpers/application_helper.rb
module ApplicationHelper
end

beta/app/helpers/directories_helper.rb
module DirectoriesHelper
end

beta/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

beta/app/views/directories/_form.html.erb
<%= form_for(@directory) do |f| %>
  <% if @directory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@directory.errors.count, "error") %> prohibited this directory from being saved:</h2>

      <ul>
      <% @directory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario_rut %><br>
    <%= f.text_field :usuario_rut %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.number_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :celular %><br>
    <%= f.number_field :celular %>
  </div>
  <div class="field">
    <%= f.label :comuna %><br>
    <%= f.text_field :comuna %>
  </div>
  <div class="field">
    <%= f.label :ciudad %><br>
    <%= f.text_field :ciudad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

beta/app/views/directories/edit.html.erb
<h1>Editing Directory</h1>

<%= render 'form' %>

<%= link_to 'Show', @directory %> |
<%= link_to 'Back', directories_path %>

beta/app/views/directories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Directories</h1>

<table>
  <thead>
    <tr>
      <th>Usuario rut</th>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Telefono</th>
      <th>Celular</th>
      <th>Comuna</th>
      <th>Ciudad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @directories.each do |directory| %>
      <tr>
        <td><%= directory.usuario_rut %></td>
        <td><%= directory.nombre %></td>
        <td><%= directory.descripcion %></td>
        <td><%= directory.telefono %></td>
        <td><%= directory.celular %></td>
        <td><%= directory.comuna %></td>
        <td><%= directory.ciudad %></td>
        <td><%= link_to 'Show', directory %></td>
        <td><%= link_to 'Edit', edit_directory_path(directory) %></td>
        <td><%= link_to 'Destroy', directory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Directory', new_directory_path %>

beta/app/views/directories/new.html.erb
<h1>New Directory</h1>

<%= render 'form' %>

<%= link_to 'Back', directories_path %>

beta/app/views/directories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario rut:</strong>
  <%= @directory.usuario_rut %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @directory.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @directory.descripcion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @directory.telefono %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @directory.celular %>
</p>

<p>
  <strong>Comuna:</strong>
  <%= @directory.comuna %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @directory.ciudad %>
</p>

<%= link_to 'Edit', edit_directory_path(@directory) %> |
<%= link_to 'Back', directories_path %>

beta/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

beta/app/views/usuario_sessions/new.html.erb
<% provide(:title, "Log in") %>
<h1>Login</h1>
<%= form_tag usuario_sessions_path, method: :post do %>
	<div class="field">
		<%= label_tag :username %></ br>
		<%= text_field_tag :username %>	
	</div>
	<div class="field">
		<%= label_tag :password %></ br>
		<%= text_field_tag :password %>	
	</div>
	 <div class="actions">
	 	<%= submit_tag "Log in" %>
	 </div>
<% end %>

beta/app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rut %><br>
    <%= f.text_field :rut %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellidos %><br>
    <%= f.text_field :apellidos %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

beta/app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

beta/app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Rut</th>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Email</th>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.rut %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellidos %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.username %></td>
        <td><%= usuario.password %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

beta/app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

beta/app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rut:</strong>
  <%= @usuario.rut %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @usuario.apellidos %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @usuario.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @usuario.password %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>